# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5b4f8d716d1f713b9ba683d9dcb58f3ad65c6c4f884b977bb400b81688fba8410d36b6b1d2ca7f86d3d7cfa57708d4e1d9a089ba2c5212a0618c59e8b926f5f

test:
  secret_key_base: 5622c0c5cc01722b49d033df40eb7ec0ccd54c947b2f6eda26dd1cf8edec168934f327518e5537dae1b5f0db1d9e932a22546e0f2271dd3735b5bff2620dfaf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
